---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1577465/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp -R Resources $DEPLOYPATH